sudo: required
dist: trusty
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
    - postfix
  firefox: "46.0"
  hosts:
      - magento2.travis
language: php
php:
  - 7.0
  - 7.1
env:
  global:
    - COMPOSER_BIN_DIR=~/bin
    - INTEGRATION_SETS=3
    - NODE_JS_VERSION=6
    - MAGENTO_HOST_NAME="magento2.travis"
  matrix:
    - TEST_SUITE=unit
    - TEST_SUITE=integration INTEGRATION_INDEX=1
    - TEST_SUITE=integration INTEGRATION_INDEX=2
    - TEST_SUITE=integration INTEGRATION_INDEX=3
    - TEST_SUITE=static
    - TEST_SUITE=js
    - TEST_SUITE=functional ACCEPTANCE_INDEX=1
    - TEST_SUITE=functional ACCEPTANCE_INDEX=2
matrix:
  exclude:
    - php: 7.0
      env: TEST_SUITE=static
    - php: 7.0
      env: TEST_SUITE=js
    - php: 7.0
      env: TEST_SUITE=functional ACCEPTANCE_INDEX=1
    - php: 7.0
      env: TEST_SUITE=functional ACCEPTANCE_INDEX=2
cache:
  apt: true
  directories:
    - $HOME/.composer/cache
    - $HOME/.nvm
    - $HOME/node_modules
    - $HOME/yarn.lock
before_install: ./dev/travis/before_install.sh
install: composer install --no-interaction --prefer-dist
before_script: ./dev/travis/before_script.sh
script: ./dev/travis/script.sh
